// EDIT DATA DI SINI
const students=[['Hanif',17,'Badminton','Tetap sederhana, terus berkembang.'],['Retno',17,'Membaca','Nikmati prosesnya.'],['Maritza',16,'Music','Do what makes you happy.'],['Naila',17,'Badminton','Small steps every day.'],['Nana',17,'Drawing','Create your own story.'],['Nurul',17,'Cooking','Be kind, always.'],['Orin',17,'Gaming','Never stop learning.'],['Putri',16,'Listening to music','Everything will be okay.'],['Royhan',17,'Gaming','Work hard, stay humble.'],['Sriyanti',17,'Badminton','Make today count.'],['Alya',17,'Reading','Believe in yourself.'],['Aisyah',16,'Photography','Collect moments, not things.'],['Kirana',17,'Writing','Your effort matters.'],['Joshua',17,'Gaming','Keep moving forward.'],['Dinda',17,'Cooking','Good things take time.'],['Hafidzul Furqan',17,'Gaming & Badminton','Be better than yesterday.'],['Faris',17,'Football','Stay focused.'],['Rizky',16,'Gaming','Enjoy the journey.'],['Salsa',17,'Drawing','Dream big.'],['Siti',17,'Reading','One day at a time.'],['Della',16,'Cooking','Make it meaningful.'],['Fina',17,'Music','Let your heart speak.'],['Rani',17,'Badminton','Keep your spirit high.'],['Vina',16,'Movies','Life is a collection of moments.'],['Aulia',17,'Reading','Learn, grow, repeat.'],['Nadia',17,'Singing','Be yourself.'],['Rafa',17,'Basketball','Never give up.'],['Ilham',16,'Gaming','Stay positive.'],['Fikri',17,'Football','Discipline beats motivation.'],['Naufal',17,'Cycling','Enjoy every ride.'],['Citra',16,'Drawing','Make something beautiful.'],['Maya',17,'Cooking','Happiness is homemade.'],['Dimas',17,'Gaming','Keep improving.'],['Rara',16,'Music','Follow your passion.'],['Bagas',17,'Badminton','Practice makes progress.'],['Zahra',17,'Reading','Be proud of your progress.']];
const moments=['https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1400&q=85','https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1400&q=85','https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1400&q=85','https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1400&q=85','https://images.unsplash.com/photo-1506869640319-fe1a24fd76dc?auto=format&fit=crop&w=1400&q=85','https://images.unsplash.com/photo-1504150558240-0b4fd8946624?auto=format&fit=crop&w=1400&q=85'];
const lessons={Senin:[['07:00–08:30','Matematika','Guru Matematika'],['08:30–10:00','Bahasa Indonesia','Guru Bahasa Indonesia'],['10:30–12:00','IPA','Guru IPA'],['13:00–14:30','PJOK','Guru PJOK']],Selasa:[['07:00–08:30','Bahasa Inggris','Guru Bahasa Inggris'],['08:30–10:00','Informatika','Guru Informatika'],['10:30–12:00','IPS','Guru IPS'],['13:00–14:30','Seni Budaya','Guru Seni Budaya']],Rabu:[['07:00–08:30','Pendidikan Agama','Guru Agama'],['08:30–10:00','Matematika','Guru Matematika'],['10:30–12:00','Bahasa Inggris','Guru Bahasa Inggris'],['13:00–14:30','PKN','Guru PKN']],Kamis:[['07:00–08:30','Bahasa Indonesia','Guru Bahasa Indonesia'],['08:30–10:00','Kimia','Guru Kimia'],['10:30–12:00','Sejarah','Guru Sejarah'],['13:00–14:30','Informatika','Guru Informatika']],Jumat:[['07:00–08:30','Fisika','Guru Fisika'],['08:30–10:00','Matematika','Guru Matematika'],['10:30–12:00','Bahasa Inggris','Guru Bahasa Inggris'],['13:00–14:30','Projek Kelas','Wali Kelas']]};
const duties={Senin:['Hanif','Retno','Maritza','Naila','Nana'],Selasa:['Nurul','Orin','Putri','Royhan','Sriyanti'],Rabu:['Alya','Aisyah','Kirana','Joshua','Dinda'],Kamis:['Faris','Rizky','Salsa','Siti','Della'],Jumat:['Fina','Rani','Vina','Aulia','Nadia']};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
// MOMENTS CAROUSEL + SWIPE
const track=$('#photoTrack'),dots=$('#photoDots');moments.forEach((src,i)=>{track.insertAdjacentHTML('beforeend',`<div class="photo-slide"><img src="${src}" alt="Moment ${i+1}"></div>`);dots.insertAdjacentHTML('beforeend',`<button class="dot ${i?'':'active'}" data-i="${i}"></button>`)});let pi=0;function showPhoto(i){pi=(i+moments.length)%moments.length;track.style.transform=`translateX(-${pi*100}%)`;$$( '.dot').forEach((d,n)=>d.classList.toggle('active',n===pi))}$('#photoPrev').onclick=()=>showPhoto(pi-1);$('#photoNext').onclick=()=>showPhoto(pi+1);$$('.dot').forEach(d=>d.onclick=()=>showPhoto(+d.dataset.i));let timer=setInterval(()=>showPhoto(pi+1),4500);let sx=0;$('#photoCarousel').ontouchstart=e=>{sx=e.changedTouches[0].clientX;clearInterval(timer)};$('#photoCarousel').ontouchend=e=>{let dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)showPhoto(pi+(dx<0?1:-1));timer=setInterval(()=>showPhoto(pi+1),4500)};
// STUDENTS: HOME 4 BERGANTI OTOMATIS
function img(i){return`https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=80&sig=${i+1}`}function card(s,i){return`<article class="student-card"><img src="${img(i)}" alt="${s[0]}"><div class="student-info"><h3>${s[0]}</h3><p>Umur: ${s[1]} tahun</p><p>Hobby: ${s[2]}</p><p class="quote">“${s[3]}”</p></div></article>`}let so=0;function highlight(){let h=$('#studentHighlight');h.innerHTML='';for(let i=0;i<4;i++)h.insertAdjacentHTML('beforeend',card(students[(so+i)%students.length],(so+i)%students.length))}highlight();setInterval(()=>{so=(so+4)%students.length;highlight()},5000);
// TABS: BUG FIX — SEMUA TAB DI-RESET, HANYA YANG DIKLIK ACTIVE
function tabs(id,data,render){const el=$('#'+id);Object.keys(data).forEach((day,i)=>{let b=document.createElement('button');b.className='tab'+(i===0?' active':'');b.textContent=day;b.dataset.day=day;b.setAttribute('role','tab');b.setAttribute('aria-selected',i===0?'true':'false');b.onclick=()=>{el.querySelectorAll('.tab').forEach(t=>{t.classList.remove('active');t.setAttribute('aria-selected','false')});b.classList.add('active');b.setAttribute('aria-selected','true');render(day)};el.appendChild(b)})}
function lesson(day){$('#lessonPanel').innerHTML=lessons[day].map(x=>`<div class="schedule-row"><div class="time">${x[0]}</div><div><div class="subject">${x[1]}</div><span class="teacher">${x[2]}</span></div></div>`).join('')}function duty(day){$('#dutyPanel').innerHTML=`<div class="duty-list">${duties[day].map(n=>`<span class="duty-person">${n}</span>`).join('')}</div>`}tabs('lessonTabs',lessons,lesson);tabs('dutyTabs',duties,duty);lesson('Senin');duty('Senin');
// MODAL SEMUA MURID & SEMUA MOMENTS
function open(id){$(id).classList.add('show');document.body.style.overflow='hidden'}function close(id){$(id).classList.remove('show');document.body.style.overflow=''}$('#allStudentsBtn').onclick=()=>{$('#allStudentsGrid').innerHTML=students.map((s,i)=>card(s,i)).join('');open('#studentsModal')};$('#allMomentsBtn').onclick=()=>{$('#fullGallery').innerHTML=moments.map((s,i)=>`<img src="${s}" data-full="${s}" alt="Moment ${i+1}">`).join('');open('#momentsModal')};$$('[data-close]').forEach(b=>b.onclick=()=>close('#'+b.dataset.close));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)close('#'+m.id)});$('#fullGallery').onclick=e=>{if(e.target.tagName==='IMG'){$('#lightboxImg').src=e.target.dataset.full;$('#lightbox').classList.add('show')}};$('#lightboxClose').onclick=()=>$('#lightbox').classList.remove('show');
$('#menuBtn').onclick=()=>$('#mobileMenu').classList.toggle('open');$('#mobileMenu').querySelectorAll('a').forEach(a=>a.onclick=()=>$('#mobileMenu').classList.remove('open'));$('#totalStudents').textContent=students.length;$('#maleStudents').textContent=18;$('#femaleStudents').textContent=students.length-18;
